hackmdPostgres:
  image: postgres
  environment:
    - POSTGRES_USER=$POSTGRES_USER
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_DB=$POSTGRES_DB
hackmd:
  image: hackmdpw
  environment:
    - POSTGRES_USER=$POSTGRES_USER
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  links:
    - hackmdPostgres:hackmdPostgres
  ports:
    - "3000:3000"
